#!/usr/bin/env bash

# Build Command #

function gecko {
  if [ "${POUNCE_VERBOSE:-}" = "true" ]
  then
    echo $@
  fi
  return 0
}

function do-build {
  local nix_file=$1
  local nix_variable=$2
  if [ "${POUNCE_VERBOSE:-}" = "true" ]
  then
    SUPPRESS_NIX=""
  else
    SUPPRESS_NIX=""
  fi
  build_output=$(nix-build --quiet --fallback --no-out-link $target -A $nix_variable)
  build_status=$?
  if [ $build_status -eq 0 ]
  then
    echo $build_output
  else
    >&2 echo $build_output
    exit 1
  fi 
}


# MAIN #

# set -eu

opcode=$1
shift

case $opcode in

build)
  gecko "Building"
  target=$1
  shift
  gecko "Building '$target' library"
  store_file=$(do-build $target library)
  gecko "Built target in '$store_file'"
  ;;

run)
  gecko "Building"
  target=$1
  shift
  gecko "Building '$target' run-script"
  store_file=$(do-build $target run-script)
  $store_file $@
  ;; 

*)
  >&2 "Unknownn command '$opcode'"
  exit 1
  ;;

esac
