#!/usr/bin/env bash

# Build Command #

function do-build {
  local nix_file=$1
  local nix_variable=$2
  build_output=$(nix-build --fallback --no-out-link $target -A $nix_variable)
  build_status=$?
  if [ $build_status -eq 0 ]
  then
    echo $build_output
  else
    >&2 echo $build_output
    exit 1
  fi 
}


# MAIN #

set -eu

opcode=$1
shift

case $opcode in

build)
  echo "Building"
  target=$1
  shift
  echo "Building '$target' library"
  store_file=$(do-build $target library)
  echo "Built target in '$store_file'"
  ;;

run)
  echo "Building"
  target=$1
  shift
  echo "Building '$target' run-script"
  store_file=$(do-build $target run-script)
  $store_file $@
  ;; 

*)
  >&2 "Unknownn command '$opcode'"
  exit 1
  ;;

esac
