#!/usr/bin/env bash

# Build Command #

function do-build {
  local target=$1
  build_output=$(nix-build --fallback --no-out-link $target)
  build_status=$?
  if [ $build_status -eq 0 ]
  then
    echo $build_output
  else
    >&2 echo $build_output
    exit 1
  fi 
}


# MAIN #

set -eu

opcode=$1
shift

case $opcode in

build)
  echo "Building"
  target=$1
  echo "Building '$target'"
  store_file=$(do-build $target)
  echo "Built target in '$store_file'"
  ;;

run)
  echo "Building"
  target=$1
  main=$2
  echo "Building '$target'"
  store_file=$(do-build $target)
  echo "Built target in '$store_file'"
  echo "Running class '$main' in '$target'"
  scala -cp $store_file "$main"
  ;; 

*)
  >&2 "Unknownn command '$target'"
  exit 1
  ;;

esac
